### ISSUE TITLE
Player control

### ISSUE THREAD

**Issue by j4cksw** [clockupstudio/ninj#2]
![player_00](https://user-images.githubusercontent.com/4876993/52163779-f33c6d00-2719-11e9-924e-9d7267b0e38d.png)

## Frame
Width: 20
Height: 20

Action| Sequence 
------------ | -------------
|Walk| 1, 2|
|Slash| 3|
|Jump| 4|
|Jump Slash| 5|

**Comment by wingyplus** [comment]
Tasks: 

- [x] walk
- [x] slash
- [ ] jump 
- [ ] jump slash

**Comment by wingyplus** [comment]
This sprite sheet information are now move to wiki page. See https://github.com/clockupstudio/ninj/wiki/Sprite-Sheets
